apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
  labels:
    app: event-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-consumer
  template:
    metadata:
      labels:
        app: event-consumer
    spec:
      containers:
      - name: event-consumer
        image: event-consumer:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event-consumer
  labels:
    app: event-consumer
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: event-consumer
  type: NodePort